---
# We can just use the worker.ign created at day1, so don't need this section, this is general way to add day2 worker
# - name: Create the ignition for day2 worker of agent installer
#   shell: |
#     oc extract -n openshift-machine-api secret/worker-user-data-managed --keys=userData --to=- > worker-agent-day2.ign
#     sudo cp worker-agent-day2.ign /var/www/html/ignition/.
#   args:
#     chdir: "{{ workdir }}"

# for OCP 4.17, ABI supports new way to add day2 worker nodes
- name: Generate the nodes-config.yaml
  template:
    src: ../templates/abi-nodes-config.yaml.j2
    dest: "{{ workdir }}/nodes-config.yaml"

- name: Create the day2-worker-nodes.iso
  environment:
    REGISTRY_AUTH_FILE: "{{ pull_secret_file }}"
  shell: oc adm --registry-config="{{ pull_secret_file }}" node-image create nodes-config.yaml
  args:
    chdir: "{{ workdir }}"

- name: Get ignition from ISO
  shell: |
    coreos-installer iso ignition show node.ppc64le.iso > worker-agent-day2.ign
    sudo cp worker-agent-day2.ign /var/www/html/ignition/.
  args:
    chdir: "{{ workdir }}"


