---
# We can just use the worker.ign created at day1, so don't need this section
- name: Create the ignition for day2 worker of agent installer
  include_tasks: agent-create.yaml

- name: Boot Workers with Day2 ISO image
  include_tasks: netboot.yaml

- name: Wait for node CSR request
  include_tasks: agent-monitor.yaml


