---
- name: Get install workdir status 
  stat:
    path: "{{ workdir }}"
  register: dir_status

- debug:
    msg: "dir status: {{ dir_status.stat.exists }}"

- name: Check if {{ workdir }} does not exist
  meta: end_play
  when: not dir_status.stat.exists|bool

- name: Day2 for assisted installer
  when: install_type == "assisted"
  include: assisted.yaml

- name: Day2 for agent based installer
  when: install_type != "assisted"
  include: agent.yaml

# - name: Day2 for SNO install
#   when: install_type == "sno" or install_type == "normal"
#   include: sno.yaml