  - name: Generate install-config.yaml
    template:
      src: ../templates/install-config.yaml.j2
      dest: "{{ workdir }}/install-config.yaml"

  - name: backup the install-config.yaml
    copy:
      src: "{{ workdir }}/install-config.yaml"
      dest: "{{ workdir }}/install-config.yaml.back"
      remote_src: yes
      force: yes

  - name: Generate agent-config.yaml
    template:
      src: ../templates/agent-config.yaml.j2
      dest: "{{ workdir }}/agent-config.yaml"
  - name: backup the agent-config.yaml
    copy:
      src: "{{ workdir }}/agent-config.yaml"
      dest: "{{ workdir }}/agent-config.yaml.back"
      remote_src: yes
      force: yes      

  - name: Create ignition for agent based install
    shell: |
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE={{ release_image_override }} {{ openshift_installer }} agent create image --log-level {{ log_level }}
    args:
      chdir: "{{ workdir }}"

  - name: Rename the ISO from agent.ppc64le.iso to agent.iso
    command: mv agent.{{ rhcos_arch }}.iso agent.iso
    args:
      chdir: "{{ workdir }}"


