  - name: Generate install-config.yaml
    template:
      src: ../templates/install-config.yaml.j2
      dest: "{{ workdir }}/install-config.yaml"

  - name: backup the install-config.yaml
    copy:
      src: "{{ workdir }}/install-config.yaml"
      dest: "{{ workdir }}/install-config.yaml.back"
      remote_src: yes
      force: yes

  - name: Create ignition files for normal OCP
    when: install_type == "normal"
    shell: |
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE={{ release_image_override }} openshift-install create ignition-configs --log-level {{ log_level }}
    args:
      chdir: "{{ workdir }}"
  
  - name: Create ignition file for SNO
    when: install_type == "sno"
    shell: |
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE={{ release_image_override }} openshift-install create single-node-ignition-config --log-level {{ log_level }}
      mv bootstrap-in-place-for-live-iso.ign sno.ign
    args:
      chdir: "{{ workdir }}"

  # - name: Add ignition kernel args to rhcos-live.iso
  #   shell: "coreos-installer iso kargs modify /usr/local/src/rhcos-live-{{ rhcos_arch }}.iso -o rhcos-live-http-ign.iso -a ignition.config.url=http://{{ helper.ipaddr }}:8080/ignition/{{ install_type }}.ign"
  #   args:
  #     chdir: "{{ workdir }}"