- set_fact:
    master_count: "{{ masters | length }}"
    worker_count: "{{ workers | default([]) | length }}"

- name: Monitor for agent based installer
  when: install_type == "agent"
  include_tasks: agent.yaml

- name: Monitor for assisted installer
  when: install_type == "assisted"
  include_tasks: assisted.yaml

- name: Monitor for SNO install
  when: install_type == "sno" or install_type == "normal"
  include_tasks: sno.yaml

- name: Wait ODF Ready
  when: assisted_deploy_odf_operator|bool
  include_tasks: wait-odf.yaml

- name: Post install process
  include_tasks: post-nfs.yaml

- name: stop httpd after installation completed
  become: true
  service:
    name: httpd
    state: stopped