- name: Set the boot order for SNO
  when: install_type == "sno" and day2_workers is not defined
  block:
  - name: Check connection
    wait_for_connection:
      delay: 15
      connect_timeout: 15
      timeout: "{{ node_connection_timeout }}"

  - name: Set boot order to disk
    shell: "sudo /usr/sbin/bootlist -m normal -o {{ masters[0].disk | default( disk ) }}"
