---
# tasks file for download ocp files
  - name: Delete OCP4 files, if requested, to download again
    file:
         state: absent
         path: "{{ item }}"
    with_items:
        - "/usr/local/src/openshift-client-linux.tar.gz"
        - "/usr/local/src/openshift-install-linux.tar.gz"
        - "/usr/local/src/rhcos-live-ppc64le.iso"
        - "/var/www/html/install/rootfs.img"
        - "/var/lib/tftpboot/rhcos/initramfs.img"
        - "/var/lib/tftpboot/rhcos/kernel"
    when: force_ocp_download or install_type != "agent"

  - name: Preparing OCP client
    when: ocp_client is defined
    block:
    - name: "Downloading OCP4 client"
      get_url:
        url: "{{ ocp_client }}"
        dest: /usr/local/src/openshift-client-linux.tar.gz
        force: true

    - name: Unarchiving OCP4 client
      unarchive:
        src: /usr/local/src/openshift-client-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes

  - name: Preparing OCP installer
    when: ocp_installer is defined
    block:
    - name: "Downloading OCP4 Installer"
      get_url:
        url: "{{ ocp_installer }}"
        dest: /usr/local/src/openshift-install-linux.tar.gz
        force: true

    - name: Unarchiving OCP4 Installer
      unarchive:
        src: /usr/local/src/openshift-install-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes

  - name: Removing files that are not needed
    file:
      path: /usr/local/bin/README.md
      state: absent

  - name: Downloading OCP4 rhcos-live.iso
    when: rhcos_iso is defined and force_ocp_download
    block:
    - name: Get CoreOS ISO URL
      shell: /usr/local/bin/openshift-install coreos print-stream-json | jq -r .architectures.ppc64le.artifacts.metal.formats.iso.disk.location
      register: rhcos_iso_url

    - name: Download CoreOS ISO
      get_url:
        url: "{{ rhcos_iso_url.stdout }}"
        dest: "/usr/local/src/rhcos-live-ppc64le.iso"
        mode: 0555

  - name: Download RHCOS images
    when: force_ocp_download or install_type != "agent"
    block:
    - name: Get CoreOS rootfs.img URL
      shell: /usr/local/bin/openshift-install coreos print-stream-json | jq -r .architectures.ppc64le.artifacts.metal.formats.pxe.rootfs.location
      register: rhcos_rootfs_url
    - name: Downloading CoreOS rootfs.img
      get_url:
        url: "{{ rhcos_rootfs_url.stdout }}"
        dest: /var/www/html/install/rootfs.img
        mode: 0555
        force: true

    - name: Get CoreOS initramfs.img URL
      shell: /usr/local/bin/openshift-install coreos print-stream-json | jq -r .architectures.ppc64le.artifacts.metal.formats.pxe.initramfs.location
      register: rhcos_initramfs_url
    - name: Downloading CoreOS initramfs.img
      get_url:
        url: "{{ rhcos_initramfs_url.stdout }}"
        dest: /var/lib/tftpboot/rhcos/initramfs.img
        mode: 0555
        force: true

    - name: Get CoreOS kernel URL
      shell: /usr/local/bin/openshift-install coreos print-stream-json | jq -r .architectures.ppc64le.artifacts.metal.formats.pxe.kernel.location
      register: rhcos_kernel_url
    - name: Downloading CoreOS kernel
      get_url:
        url: "{{ rhcos_kernel_url.stdout }}"
        dest: /var/lib/tftpboot/rhcos/kernel
        mode: 0555
        force: true