---
- name: create grub2 block for Assisted/Agent/SNO
  when: install_type != "normal"
  blockinfile:
    marker: ""
    content: |
      if [ ${net_default_mac} == {{ mac }} ]; then
      default=0
      fallback=1
      timeout=1
      menuentry "CoreOS (BIOS)" {
         echo "Loading kernel"
         linux "/rhcos/kernel" {{ ip_config }} rd.neednet=1 ignition.platform.id=metal ignition.firstboot {{ coreos_inst_url }} ignition.config.url={{ ignition_url }}/{{ ignition }}

         echo "Loading initrd"
         initrd  "/rhcos/initramfs.img"
      }
      fi
    dest: /var/lib/tftpboot/boot/grub2/grub.cfg

- name: create grub2 block for normal OCP
  when: install_type == "normal"
  blockinfile:
    marker: ""
    content: |
      if [ ${net_default_mac} == {{ mac }} ]; then
      default=0
      fallback=1
      timeout=1
      menuentry "CoreOS (BIOS)" {
         echo "Loading kernel for {{ name }}"
         linux "/rhcos/kernel" {{ ip_config }} rd.neednet=1 {{ multipath }} coreos.inst=yes coreos.inst.install_dev={{ mdisk }} {{ coreos_inst_url }} coreos.inst.ignition_url={{ ignition_url }}/{{ role }}.ign ignition.config.url={{ ignition_url }}/first-boot-ppc64le-{{ name }}.ign

         echo "Loading initrd"
         initrd  "/rhcos/initramfs.img"
      }
      fi
    dest: /var/lib/tftpboot/boot/grub2/grub.cfg

- name: Copy first-boot-ppc64le-{{ name }}.ign to /www/html/ignition
  when: install_type == "normal"
  template:
    src: templates/first-boot-ppc64le.ign.j2
    dest: "/var/www/html/ignition/first-boot-ppc64le-{{ name }}.ign"
