---
# file: main.yaml

  - name: set facts
    include: set_facts.yaml

  - name: Setup required services
    become: true
    include: setup_services.yaml

  - name: Download OCP files
    include: download_files.yaml

  - name: Setup Local Registry
    when: setup_registry is defined and setup_registry.deploy
    block:
    - name: Install registry packages
      become: true
      package:
        name: "{{ registry }}"
        state: present

    - name: Setup Registry
      include: setup_registry.yaml

  - name: Start firewalld service
    become: true
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Open up firewall ports
    become: true
    firewalld:
      permanent: yes
      immediate: yes
      state: enabled
      port: "{{ item[0] }}"
    delegate_to: "{{ item[1] }}"
    run_once: true
    with_nested:
      - "{{ ports }}"
      - "{{ ansible_play_batch }}"

  - name: Best effort SELinux repair - Apache
    become: true
    shell: "restorecon -vR /var/www/html || true"

  - name: Systemd daemon reload
    become: true
    systemd:
      daemon_reload: yes

  - name: Starting services
    become: true
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - "{{ services }}"

  - name: start stand along dhcp if it is enabled
    become: true
    service: 
      name: dhcpd
      enabled: yes
      state: started
    when: enable_dhcp

  # - name: Set the local resolv.conf file
  #   become: true
  #   template:
  #     src: ../templates/resolv.conf.j2
  #     dest: /etc/resolv.conf

  - name: stop haproxy when there is no need
    become: true
    service:
      name: haproxy
      state: stopped
    when: dhcp.api_vip is defined or ( masters | length == 1 and bootstrap is not defined )
    
