---
# defaults file

workdir: ~/ocp4-ai
rhcos_arch: ppc64le
ocp_client_arch: ppc64le
log_level: info
release_image_override: ""
cni_network_provider: OVNKubernetes
storage_type: ""
node_connection_timeout: 2700
openshift_installer: "openshift-install"
assisted_token: ""
