---
# defaults file

workdir: ~/workdir-ocp4-ai
rhcos_arch: ppc64le
ocp_client_arch: ppc64le
log_level: info
release_image_override: ""
proxy_url: ""
no_proxy: ""
enable_local_registry: false
cni_network_provider: OVNKubernetes
storage_type: ""
node_connection_timeout: 2700
openshift_installer: "openshift-install"
disk: "/dev/sda"
# using static IP
static_ip: false
################################
# disk encryption
fips_compliant: false
luks:
   enabled: false
   filesystem_device: /dev/mapper/root
   format: xfs
   wipeFileSystem: true
   device: /dev/disk/by-partlabel/root
   label: luks-root
   options:
      - --cipher
      - aes-cbc-essiv:sha256
   wipeVolume: true
   name: root
disk_encryption: "{{ luks.enabled }}"
#####################################
assisted_url: "https://api.openshift.com/api/assisted-install/v2"
assisted_token: ""
assisted_exist_cluster: false
# deploy with dual IP stack
assisted_net_dualstack: false
# deploy OpenShift Data Foundation
assisted_deploy_odf_operator: false
####################################
force_ocp_download: false
pull_secret: "{{ lookup('file', '~/.openshift/pull-secret') | from_json | to_json }}"
public_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
