---
# handlers file for tester
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart nfs
  service:
    name: nfs-server
    state: restarted

- name: restart haproxy
  service:
    name: haproxy
    state: restarted

