---
# defaults file

workdir: ~/ocp4-ai
rhcos_arch: ppc64le
ocp_client_arch: ppc64le
log_level: info
release_image_override: ""
cni_network_provider: OVNKubernetes
#cni_network_provider: OpenshiftSDN
storage_type: ""
node_connection_timeout: 2700
http_port: 8000
disk: /dev/sda
force_ocp_download: false
openshift_installer: "openshift-install"
kubeconfig_file: "{{ workdir }}/kubeconfig"
# disk encryption
disk_encryption: false
# Using static IP
static_ip: false
#####################################
assisted_token: ""
assisted_exist_cluster: false
# deploy with dual IP stack
assisted_net_dualstack: false
# deploy OpenShift Data Foundation
assisted_deploy_odf_operator: false
####################################
pull_secret: "{{ lookup('file', '~/.openshift/pull-secret') | from_json | to_json }}"
public_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

