---
# Monitor day2 worker nodes
- hosts: bastion
  vars_files:
    - defaults/main.yaml
  vars:
    kubeconfig_file: "{{ workdir}}/auth/kubeconfig"
  tasks:
  - name: Monitor add day2 workers
    include_tasks: roles/day2/tasks/assisted-monitor.yaml