---
# file: main.yml
- name: Cleanup old files
  hosts: bastion
  gather_facts: false
  any_errors_fatal: false
  tasks:
    - name: Clean up work directory
      file: 
        path: "{{ workdir }}/"
        state: absent

- name: Setup services for bastion
  hosts: bastion
  vars_files:
  - defaults/main.yaml
  handlers:
  - import_tasks: handlers/main.yml
  gather_facts: true
  any_errors_fatal: true
  become: true
  roles:
  - services

- name: Create OCP ignition file
  hosts: bastion
  vars_files:
  - defaults/main.yaml
  gather_facts: false
  any_errors_fatal: true
  tasks:
  roles:
  - ignition
    
