---
# file: main.yml
- name: Setup services and ignition for day1
  when: day2_workers is not defined
  import_playbook: setup-day1.yaml

- name: Setup services and ignition for day2
  when: day2_workers is defined and day2_workers|length > 0
  import_playbook: setup-day2.yaml

