---
# file: add-workers.yaml

- name: Setup services for bastion
  hosts: bastion
  vars_files:
    - defaults/main.yaml
  handlers:
  - import_tasks: handlers/main.yml
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    force_ocp_download: false
  roles:
  - services

- name: Do day2 tasks to create the ignition and other files for day2 worker
  hosts: bastion
  vars_files:
    - defaults/main.yaml
  become: false
  gather_facts: false
  any_errors_fatal: true
  vars:
    kubeconfig_file: "{{ workdir}}/auth/kubeconfig"
    master_count: "{{ masters | length }}"
    worker_count: "{{ workers | default([]) | length }}"
    day2_worker_count: "{{ day2_workers | default([]) | length }}"
  tasks:
  - name: Create day2 workers ignition
    include_tasks: roles/day2/tasks/create.yaml
