---
# file: main.yml
- name: Monitor OCP installation progress
  hosts: localhost
  vars_files:
    - defaults/main.yaml
  gather_facts: true
  any_errors_fatal: true
  vars:
    kubeconfig_file: "{{ workdir}}/kubeconfig"
  roles:
  - monitor
