---
# defaults file

rhcos_arch: ppc64le
ocp_client_arch: ppc64le
cni_network_provider: OVNKubernetes
kubeconfig_file: "{{ workdir }}/auth/kubeconfig"
assisted_token: ""
####################################
pull_secret: "{{ lookup('file', '~/.openshift/pull-secret') | from_json | to_json }}"
public_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"